### ISSUE TITLE
报找不到R类的错

### ISSUE THREAD

**Issue by 4iconfont** [duduhuang88/qxml#1]

**Comment by 4iconfont** [comment]
跟滴滴的booster冲突了，屏蔽掉booster就没问题

**Comment by duduhuang88** [comment]
目前生成的View类使用的是R.layout.xxxx引用R类，省去R类变化重新生成的过程，看了下booster，只要不使用 classpath "com.didiglobal.booster:booster-transform-r-inline:$booster_version" 内联R类即可
