### ISSUE TITLE
Caused by: java.lang.RuntimeException: 请先设置ANDROID_HOME环境变量

### ISSUE THREAD

**Issue by cLqzf** [duduhuang88/qxml#3]
Caused by: java.lang.RuntimeException: 请先设置ANDROID_HOME环境变量

**Comment by duduhuang88** [comment]
因为需要获取Android sdk，所以默认获取的是ANDROID_HOME设置的路径，一般AS环境变量会配置ANDROID_HOME，可以先确认你的电脑上有设置ANDROID_HOME，如果有却仍然找不到，请再回复下

**Comment by duduhuang88** [comment]
请使用1.3.2版本，不再要求设置ANDROID_HOME变量
