### ISSUE TITLE
下面有对勾怎么解决

### ISSUE THREAD

**Issue by mxdlsm** [duduhuang88/qxml#4]
![WechatIMG148](https://user-images.githubusercontent.com/22886455/178194973-3aad5438-a915-43f3-be86-5da18da8a3b7.jpeg)

**Comment by duduhuang88** [comment]
这个勾可以在
qxml {
    viewDebug false		 //是否在转换的View上显示标志，默认false
}
这里设置是否显示，这个配置是为了可以直观的看出哪一些View被qxml转换了而设置的
如果没有设置为True而出现的话，试下clean后重新运行（可能是构建缓存导致，clean后会删除缓存）
如果clean后还是会出现的话，可以看下是否在layout xml文件里声明了app:qxml_debug=“true”
如果没有声明app:qxml_debug，你方便贴出来一个最简单的可复现layout xml吗？
